---
repos:
  - repo: https://github.com/petalmd/dockerfile-pre-commit
    rev: v1.0
    hooks:
      - id: dockerlint

  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: debug-statements
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: name-tests-test
      - id: fix-encoding-pragma
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: check-executables-have-shebangs

  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
      - id: python-bandit-vulnerability-check
        files: .py$

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=120]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.78.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_validate
      - id: terraform_tflint
        args:
          - --args=--minimum-failure-severity=error
        verbose: true
      - id: terraform_tfsec
      - id: terraform_checkov
      - id: terrascan
      - id: infracost_breakdown
        args:
          - --args=--path=aws
        verbose: true
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.13.0
    hooks:
      - id: pip-compile

  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.77.4
    hooks:
      - id: cfn-python-lint
        files: path/to/cfn/dir/.*\.(json|yml|yaml)$

  - repo: local
    hooks:
      - id: tests
        name: run tests
        entry: pytest -v
        language: system
        types: [python]
        stages: [push]

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.15.0
    hooks:
      - id: ansible-lint
        name: Ansible-lint
        description: This hook runs ansible-lint.
        entry: ansible-lint --force-color
        language: python
        # do not pass files to ansible-lint, see:
        # https://github.com/ansible-community/ansible-lint/issues/611
        pass_filenames: false
        always_run: true

  - repo: https://github.com/radix-ai/auto-smart-commit
    rev: v0.1.0
    hooks:
    - id: auto-smart-commit
      args:
      - --jira-smart-commit

  # Add a hook for SAST using the `safety` tool
  - repo: https://github.com/pyupio/safety
    rev: 1.10.3
    hooks:
      - id: safety
        args: ['check', '--full-report']
        description: "Scan dependencies for known security vulnerabilities using safety"
        language: python
        types: [dependency]

  # Add a hook for code formatting using `isort`
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        args: ['-rc']
        description: "Sort python imports with isort"
        language: python
        types: [python]

  # Add a hook for checking code complexity using `radon`
  - repo: https://github.com/wemake-services/wemake-python-styleguide
    rev: v0.15.4
    hooks:
      - id: radon
        args: ["mi", "--show-complexity", "--min", "10", "."]
        description: "Check code complexity with radon"
        language: python
        types: [python]

  # Add a hook for checking type hints using `mypy`
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        args: ['--config-file', 'mypy.ini', '.']
        language: python
        types: [python]

  # Add a hook for checking for sensitive data using `truffleHog`
  - repo: https://github.com/pre-commit/mirrors-trufflehog
    rev: v0.5.7
    hooks:
      - id: trufflehog
        args: ['--regex', '--entropy=False']
        description: "Scan for secrets using trufflehog"
        language: python
        types: [file]

  # Add a hook for checking for hard-coded AWS secrets
  - repo: https://github.com/nccgroup/ScoutSuite
    rev: v5.9.0
    hooks:
      - id: scout-aws-secrets
        name: Scout Suite - AWS Secrets
        entry: scout aws secrets
        description: Check for hard-coded AWS secrets using Scout Suite
        language: python
        types: [file]

  # Add a hook for checking for hard-coded Azure secrets
  - repo: https://github.com/nccgroup/ScoutSuite
    rev: v5.9.0
    hooks:
      - id: scout-azure-secrets
        name: Scout Suite - Azure Secrets
        entry: scout azure secrets
        description: Check for hard-coded Azure secrets using Scout Suite
        language: python
        types: [file]

  # Add a hook for checking for hard-coded GCP secrets
  - repo: https://github.com/nccgroup/ScoutSuite
    rev: v5.9.0
    hooks:
      - id: scout-gcp-secrets
        name: Scout Suite - GCP Secrets
        entry: scout gcp secrets
        description: Check for hard-coded GCP secrets using Scout Suite
        language: python
        types: [file]

  - repo: https://github.com/simonkowallik/sls-cognito-cleanup-plugin
    rev: v1.1.2
    hooks:
      - id: sls-cognito-cleanup-plugin
        name: SLS Cognito Cleanup Plugin
        entry: sls_cognito_cleanup_plugin.cleanup
        language: python
        types: [python]
        always_run: true
        verbose: true
      - id: sls-cognito-cleanup-plugin-iam
        name: SLS Cognito Cleanup Plugin IAM
        entry: sls_cognito_cleanup_plugin.iam_cleanup
        language: python
        types: [python]
        always_run: true
        verbose: true
